// <auto-generated />
using System;
using Merit_Tracker.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Merit_Tracker.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    [Migration("20250711043457_add_merit_table")]
    partial class add_merit_table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Merit_Tracker.Models.MeritModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("DatabaseID")
                        .HasColumnType("integer")
                        .HasColumnName("DatabaseID");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("DateOfIssue");

                    b.Property<int>("HousePoints")
                        .HasColumnType("integer")
                        .HasColumnName("HousePoints");

                    b.Property<int>("IssuerID")
                        .HasColumnType("integer")
                        .HasColumnName("IssuerID");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("StudentName");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("Value");

                    b.HasKey("Id");

                    b.ToTable("Merits");
                });

            modelBuilder.Entity("Merit_Tracker.Models.UserModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Username");

                    b.HasKey("ID");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
