// <auto-generated />
using System;
using Merit_Tracker.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Merit_Tracker.Migrations
{
    [DbContext(typeof(AppDatabaseContext))]
    [Migration("20250729093111_year_level")]
    partial class year_level
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("Merit_Tracker.Models.DatabaseModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("DatabaseID")
                        .HasColumnType("integer")
                        .HasColumnName("DatabaseID");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Name");

                    b.Property<int>("UserID")
                        .HasColumnType("integer")
                        .HasColumnName("UserID");

                    b.HasKey("Id");

                    b.ToTable("Databases");
                });

            modelBuilder.Entity("Merit_Tracker.Models.MeritModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("Id"));

                    b.Property<int>("DatabaseID")
                        .HasColumnType("integer")
                        .HasColumnName("DatabaseID");

                    b.Property<DateTime>("DateOfIssue")
                        .HasColumnType("timestamptz")
                        .HasColumnName("DateOfIssue");

                    b.Property<int>("HousePoints")
                        .HasColumnType("integer")
                        .HasColumnName("HousePoints");

                    b.Property<int>("IssuerID")
                        .HasColumnType("integer")
                        .HasColumnName("IssuerID");

                    b.Property<string>("IssuerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("IssuerName");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("StudentName");

                    b.Property<int>("Value")
                        .HasColumnType("integer")
                        .HasColumnName("Value");

                    b.Property<string>("Yearlevel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("YearLevel");

                    b.HasKey("Id");

                    b.ToTable("Merits");
                });

            modelBuilder.Entity("Merit_Tracker.Models.UserModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("ID"));

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Password");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("Username");

                    b.HasKey("ID");

                    b.ToTable("users");
                });
#pragma warning restore 612, 618
        }
    }
}
